### ISSUE TITLE
FATAL: Max client connections reached 

### ISSUE THREAD

**Issue by emrgnt-cmplxty** [supabase/vecs#77] opened 2024-02-15 03:12 UTC
**Describe the bug**
I am intermittently experiencing the error shown below:

```bash
(psycopg2.OperationalError) connection to server at "aws-0-us-west-1.pooler.supabase.com" (54.177.55.191), port 5432 failed: FATAL: Max client connections reached (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**To Reproduce**
I am ingesting a reasonable number of requests with a FastAPI implementation in python. The issue could be due to an incorrect implementation, but I could not gather if this was the case and if so, why, from the documentation.

The snippet below shows how I have implemented the PGVectorDB
```python
...
from vecs.client import Client
from vecs.collection import Collection
...

class PGVectorDB(VectorDBProvider):
    def __init__(self) -> None:
        super().__init__()
        try:
            import vecs
        except ImportError:
            raise ValueError(
                f"Error, PGVectorDB requires the vecs library. Please run `poetry add vecs`."
            )
        try:
            user = os.getenv("PGVECTOR_USER")
            password = os.getenv("PGVECTOR_PASSWORD")
            host = os.getenv("PGVECTOR_HOST")
            port = os.getenv("PGVECTOR_PORT")
            db_name = os.getenv("PGVECTOR_DBNAME")

            DB_CONNECTION = (
                f"postgresql://{user}:{password}@{host}:{port}/{db_name}"
            )
            self.vx: Client = vecs.create_client(DB_CONNECTION)
        except Exception as e:
            raise ValueError(
                f"Error {e} occurred while attempting to connect to the pgvector provider."
            )
        self.collection: Optional[Collection] = None

    def initialize_collection(
        self, collection_name: str, dimension: float
    ) -> None:
        self.collection = self.vx.get_or_create_collection(
            name=collection_name, dimension=dimension
        )

    def upsert(self, entry: VectorEntry, commit=True) -> None:
        if self.collection is None:
            raise ValueError(
                "Please call `initialize_collection` before attempting to run `upsert`."
            )

        self.collection.upsert(
            records=[(entry.id, entry.vector, entry.metadata)]
        )
```
The database is being created in multiple threads due to the nature of how the FastAPI is configured.

**Expected behavior**
I do not expect to encounter this error. I am only communicating with the database with four worker threads.

**Versions:**
- Supabase defaults

**Additional context**
It would be great if there was more documentation around how to use the vecs library in production.

**Comment by olirice** [comment] 2024-02-21 18:47
If you're repeatedly instantiating that class without calling [Client.disconnect()](https://supabase.github.io/vecs/0.4/api/#disconnect) or using as a context manager, its possible that you'd steadily leak connections. It's also possible that the issue is unrelated to vecs.

If you think you're disposing of the connection correctly then the best thing to do would be open a support ticket at supabase.com/support so we have access to logs to figure out what all the connections are doing

I'm going to close this for now as it doesn't relate to the core of this project but am happy to assist you in this closed issue or via supabase support if you open a ticket

**Closed by olirice** 2024-02-21 18:47 UTC
